name: "PR Checks for `main`"
on:
  pull_request:
    types:
      - opened        # initially opened
      - reopened      # closed then opened again
      - synchronize   # any changes pushed
    branches:
      - main
    paths-ignore: # Only run checks on changes to code
      - "**/docs/*"
      - "*/README.md"

jobs:
  build-app-android:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    steps:
      - name: Setup
        uses: Pointyware/.github/.github/actions/checkout-java-gradle@69eb71701edc0705172789b1299946fd27fcadac
      - name: Run Debug Unit Tests
        run: |
          ./gradlew :core-data:generateSqlDelightInterface --no-build-cache --no-configuration-cache && \
            ./gradlew :app-android:testDebugUnitTest

  build-app-desktop:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    steps:
      - name: Setup
        uses: Pointyware/.github/.github/actions/checkout-java-gradle@69eb71701edc0705172789b1299946fd27fcadac
      - name: Build Desktop App
        run: |
          ./gradlew :core-data:generateSqlDelightInterface --no-build-cache --no-configuration-cache && \
            ./gradlew :app-desktop:desktopTest
